package com.eltaieb.microservice.base.model;

public enum ErrorMessageCode {
	
	OPERATION_COMPLETED_SUCCESSFULLY("00","OPERATION_DONE_SUCCESSFULLY"),
	PUBLIC_USER_EMAIL_ALREADY_REGISTERED("01","PUBLIC_USER_EMAIL_ALREADY_REGISTERED"),
	PUBLIC_USER_PASSWORD_IS_REQIORED("02","PUBLIC_USER_PASSWORD_IS_REQIORED"),
	PUBLIC_USER_USER_NAME_IS_REQIORED("03","PUBLIC_USER_USER_NAME_IS_REQIORED"),
	PUBLIC_USER_PASSWORD_LENGTH_ERROR("04","PUBLIC_USER_PASSWORD_LENGTH_ERROR"),
	PUBLIC_USER_PASSWORD_COULD_NOT_BE_ONLY_SPACES("05","PUBLIC_USER_PASSWORD_COULD_NOT_BE_ONLY_SPACES"),
	PUBLIC_USER_BIRTHDAY_COULD_NOT_BE_IN_THE_FUTURE("06","PUBLIC_USER_BIRTHDAY_COULD_NOT_BE_IN_THE_FUTURE"),
	PUBLIC_USER_AGE_IS_NOT_ALLOWED("07","PUBLIC_USER_AGE_IS_NOT_ALLOWED"), 
	PUBLIC_USER_BIRTHDAY_IS_REQIORED("08","PUBLIC_USER_BIRTHDAY_IS_REQIORED"),
	USER_NAME_NOT_FOUND("09","USER_NAME_NOT_FOUND"), 
	INVALID_USER_NAME_OR_PASSWORD("10","INVALID_USER_NAME_OR_PASSWORD"), 
	ACCOUNT_IS_LOCKED("11","ACCOUNT_IS_LOCKED"),
	ACCOUNT_IS_DISABLED("12","ACCOUNT_IS_DISABLED"),
	ACCOUNT_IS_EXPIRED("13","ACCOUNT_IS_EXPIRED"),
	AUTHENTICATION_ERROR("14","AUTHENTICATION_ERROR"), 
	GENERAL_BACKEND_ERROR("15","GENERAL_BACKEND_ERROR"),
	NO_FACEBOOK_ACCESS_TOKE_PROVIDED("16","NO_FACEBOOK_ACCESS_TOKE_PROVIDED"), 
	NO_GOOGLE_CLIENT_ID_TOKEN_PROVIDED("17","NO_GOOGLE_CLIENT_ID_TOKEN_PROVIDED"), 
	ERROR_WHILE_AUTHENTICATING_WITH_FACEBOOK("18","ERROR_WHILE_AUTHENTICATING_WITH_FACEBOOK"),
	PUBLIC_USER_FIRST_NAME_IS_REQIORED("19","PUBLIC_USER_FIRST_NAME_IS_REQIORED"), 
	FACEBOOK_TOKEN_IS_EXPIRED("20","FACEBOOK_TOKEN_IS_EXPIRED"), 
	GOOGLE_CLIENT_ID_TOKEN_IS_EXPIRED("22", "GOOGLE_CLIENT_ID_TOKEN_IS_EXPIRED"), 
	DOUBLICATE_USERNAME_OWNERSHIP_PRETENTION("23","DOUBLICATE_USERNAME_OWNERSHIP_PRETENTION"), 
	INVALID_EMAIL_TOKEN_PROVIDED("24","INVALID_EMAIL_TOKEN_PROVIDED"), 
	EMAIL_TOKEN_HAS_BEEN_EXPIRED("25","EMAIL_TOKEN_HAS_BEEN_EXPIRED"), 
	UNKNOWN_VERIFICATION_TOKEN_PROVIDED("26","UNKNOWN_VERIFICATION_TOKEN_PROVIDED"), 
	UNKNOWN_VERIFICATION_CODE_PROVIDED("27","UNKNOWN_VERIFICATION_CODE_PROVIDED"), 
	TOKEN_ALREADY_CONSUMED("28","TOKEN_ALREADY_CONSUMED"), 

	// {0}
	MIN_DURATION_IN_MINUTES_BETWEEN_VERIFICATION_TOKEN_SEND_EMAIL_VIOLATED("26","MIN_DURATION_IN_MINUTES_BETWEEN_VERIFICATION_TOKEN_SEND_EMAIL_VIOLATED"),
	USER_NAME_IS_ALREADY_VERIFIED("27","USER_NAME_IS_ALREADY_VERIFIED"), 
	WRONG_OLD_PASSWORD("28","WRONG_OLD_PASSWORD"), 
	ACCOUNT_TYPE_IS_NOT_ELIGIBLE_FOR_PASSWORD_CHANGE("29","ACCOUNT_TYPE_IS_NOT_ELIGIBLE_FOR_PASSWORD_CHANGE"), 
	SOMETHING_WENT_WRONG("30","ACCOUNT_TYPE_IS_NOT_ELIGIBLE_FOR_PASSWORD_CHANGE"), 
	OLD_PASSWORD_AND_NEW_PASSWORD_SHOULD_NOT_BE_SAME("31","OLD_PASSWORD_AND_NEW_PASSWORD_SHOULD_NOT_BE_SAME"), 
	USER_ALREADY_VERIFIED("32","USER_ALREADY_VERIFIED"),
	USER_IS_NOT_VERIFIED_VERIFY_FIRST("33","USER_IS_NOT_VERIFIED_VERIFY_FIRST"),
	
	
	
	
	
	
	
	;
	
	
	final private String code;
	final private String messageKey;
	
	

	public String getMessageKey() {
		return messageKey;
	}

	 

	 
	
 
	
	ErrorMessageCode(String code,String messageKey)
	{
		this.code= code;
		this.messageKey = messageKey;
	}
	
	public String getCode() {
		return code;
	}
	
}
